services:
    server:
        image: "docker.io/ghoulouis/test-rofl:latest"
        platform: linux/amd64
        environment:
            - IN_ROFL=TRUE
            - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
            - TELEGRAM_GROUP_ID=${TELEGRAM_GROUP_ID}
        # volumes:
        #     - /run/rofl-appd.sock:/run/rofl-appd.sock
